name:                MP3-Metadata
version:             0.1.0.0
# synopsis:
# description:
homepage:            https://github.com/kapkekes/MP3-Metadata#readme
license:             BSD3
author:              Dmitriy Vashurin
maintainer:          kapkekes@example.com
copyright:           2021 Author name here
# category:

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- data-default
- lens
- monomer
- text
- text-show

executables:
  app:
    source-dirs:      application
    main:             Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
